version: '3'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=boat_tracker
      - MONGO_USERNAME=boat_user
      - MONGO_PASSWORD=boat_password
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=boat_user
      - MONGO_INITDB_ROOT_PASSWORD=boat_password
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: